[package]
name = "bevy_mod_dynamic"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "bevy_mod_dynamic_client", "example"]

[dependencies]
bevy = "0.14.2"
slotmap = "1.0.7"
wasmer = "4.3.7"
